
USE [ProjectDB_Lab2];
GO

DROP TABLE IF EXISTS dbo.ChatTasks;
DROP TABLE IF EXISTS dbo.UserChatRoles;
DROP TABLE IF EXISTS dbo.Tasks;
DROP TABLE IF EXISTS dbo.Labels;
DROP TABLE IF EXISTS dbo.Roles;
DROP TABLE IF EXISTS dbo.Chats;
DROP TABLE IF EXISTS dbo.Users;
GO

CREATE TABLE dbo.Users (
    UserId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Chats (
    ChatId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Roles (
    RoleId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE dbo.Labels (
    LabelId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ChatId INT NOT NULL,
    Name NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_Labels_Chat FOREIGN KEY (ChatId) REFERENCES dbo.Chats(ChatId)
);

CREATE TABLE dbo.Tasks (
    TaskId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Title NVARCHAR(200) NOT NULL,
    ChatId INT NOT NULL,
    UserId INT NOT NULL,
    LabelId INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Tasks_Chat FOREIGN KEY (ChatId) REFERENCES dbo.Chats(ChatId),
    CONSTRAINT FK_Tasks_User FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId),
    CONSTRAINT FK_Tasks_Label FOREIGN KEY (LabelId) REFERENCES dbo.Labels(LabelId)
);

CREATE TABLE dbo.UserChatRoles (
    UserChatRoleId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    ChatId INT NOT NULL,
    RoleId INT NOT NULL,
    CONSTRAINT FK_UserChatRoles_User FOREIGN KEY (UserId) REFERENCES dbo.Users(UserId),
    CONSTRAINT FK_UserChatRoles_Chat FOREIGN KEY (ChatId) REFERENCES dbo.Chats(ChatId),
    CONSTRAINT FK_UserChatRoles_Role FOREIGN KEY (RoleId) REFERENCES dbo.Roles(RoleId)
);

CREATE TABLE dbo.ChatTasks (
    ChatTaskId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ChatId INT NOT NULL,
    TaskId INT NOT NULL,
    CONSTRAINT FK_ChatTasks_Chat FOREIGN KEY (ChatId) REFERENCES dbo.Chats(ChatId),
    CONSTRAINT FK_ChatTasks_Task FOREIGN KEY (TaskId) REFERENCES dbo.Tasks(TaskId)
);
GO
